#!/usr/bin/env python3

import argparse
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

def load_fes_2d(filename):
    """
    Reads a 2D FES output file generated by do_block_fes_v2.py.
    Returns grid values for X, Y, FES (in kcal/mol) and Error (in kcal/mol).
    """
    x_vals, y_vals, fes_vals, err_vals = [], [], [], []
    
    with open(filename, 'r') as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.strip().split()
            if len(parts) >= 4:
                x = float(parts[0])
                y = float(parts[1])
                
                # Check for Inf or NaN values
                fes = np.nan if parts[2] in ['Inf', 'NaN'] else float(parts[2]) / 4.184
                err = np.nan if parts[3] in ['Inf', 'NaN'] else float(parts[3]) / 4.184
                
                x_vals.append(x)
                y_vals.append(y)
                fes_vals.append(fes)
                err_vals.append(err)
                
    if not x_vals:
        raise ValueError(f"No valid data found in {filename}")

    x_unique = np.unique(x_vals)
    y_unique = np.unique(y_vals)
    
    nx = len(x_unique)
    ny = len(y_unique)
    
    # Reshape into 2D grids (Y-rows, X-cols)
    grid_fes = np.full((ny, nx), np.nan)
    grid_err = np.full((ny, nx), np.nan)
    
    x_map = {val: idx for idx, val in enumerate(x_unique)}
    y_map = {val: idx for idx, val in enumerate(y_unique)}
    
    for x, y, f, e in zip(x_vals, y_vals, fes_vals, err_vals):
        i = y_map[y]
        j = x_map[x]
        grid_fes[i, j] = f
        grid_err[i, j] = e
        
    # Shift minimum FES to 0
    min_fes = np.nanmin(grid_fes)
    if not np.isnan(min_fes):
        grid_fes -= min_fes
        
    return x_unique, y_unique, grid_fes, grid_err

def main():
    parser = argparse.ArgumentParser(description="Plot 2D FES surface and statistical error map.")
    parser.add_argument("-f", "--file", required=True, help="Input fes_2D.dat file")
    parser.add_argument("-o", "--out", default="plot_2D_fes.png", help="Output PNG file")
    parser.add_argument("--xlabel", default="CV1", help="X-axis label")
    parser.add_argument("--ylabel", default="CV2", help="Y-axis label")
    parser.add_argument("--title", default="2D Free Energy Surface", help="Plot title")
    parser.add_argument("--emax", type=float, default=40.0, help="Energy cutoff in kcal/mol")
    parser.add_argument("--levels", type=int, default=30, help="Number of contour levels for smoothness")
    parser.add_argument("--nm-to-a-x", action="store_true", help="Convert X axis from nm to Angstroms")
    parser.add_argument("--nm-to-a-y", action="store_true", help="Convert Y axis from nm to Angstroms")
    
    args = parser.parse_args()

    x, y, grid_fes, grid_err = load_fes_2d(args.file)

    if args.nm_to_a_x:
        x = x * 10.0
    if args.nm_to_a_y:
        y = y * 10.0

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))

    # Define contour levels based on emax
    levels_fes = np.linspace(0, args.emax, args.levels)

    # --- 1. FES Plot ---
    cmap_fes = mpl.colormaps['viridis'].copy()
    cmap_fes.set_bad(color='white')

    # Use contourf for smooth interpolated coloring
    im1 = ax1.contourf(x, y, grid_fes, levels=levels_fes, cmap=cmap_fes, extend='max')
    cbar1 = fig.colorbar(im1, ax=ax1, format="%.2f")
    cbar1.set_label("Free Energy (kcal/mol)", fontsize=12)

    # Add black contour lines for topological detail
    contour_step = 1.0
    ax1.contour(x, y, grid_fes, levels=np.arange(0, args.emax + 1, contour_step), colors='black', linewidths=0.5, alpha=0.5)

    ax1.set_xlabel(args.xlabel, fontsize=12)
    ax1.set_ylabel(args.ylabel, fontsize=12)
    ax1.set_title(f"{args.title} - FES", fontsize=14)

    # --- 2. Error Plot ---
    # Mask errors where FES exceeds emax or is NaN/Inf
    masked_err = np.where((grid_fes <= args.emax) & (~np.isnan(grid_err)), grid_err, np.nan)

    cmap_err = mpl.colormaps['magma_r'].copy()
    cmap_err.set_bad(color='white')

    # Safely determine error bounds
    valid_err = masked_err[~np.isnan(masked_err)]
    if len(valid_err) > 0:
        vmax_err = np.percentile(valid_err, 98)
        vmin_err = np.min(valid_err)
    else:
        vmin_err, vmax_err = 0.0, 1.0

    # Ensure min and max aren't identical to avoid contourf crashing
    if vmax_err <= vmin_err:
        vmax_err = vmin_err + 0.1

    levels_err = np.linspace(vmin_err, vmax_err, args.levels)

    # Use contourf for smooth error map
    im2 = ax2.contourf(x, y, masked_err, levels=levels_err, cmap=cmap_err, extend='max')
    cbar2 = fig.colorbar(im2, ax=ax2, format="%.2f")
    cbar2.set_label("Statistical Error (kcal/mol)", fontsize=12)

    ax2.set_xlabel(args.xlabel, fontsize=12)
    ax2.set_ylabel(args.ylabel, fontsize=12)
    ax2.set_title(f"{args.title} - Error Map", fontsize=14)

    plt.tight_layout()
    plt.savefig(args.out, dpi=300)
    print(f"2D FES Plot saved to {args.out}")

if __name__ == "__main__":
    main()
